// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8fbSyzV5yxSvDkEmwkD9GAw94sftMq_I',
    appId: '1:148842405278:web:87a63d4eeb5678685aca8f',
    messagingSenderId: '148842405278',
    projectId: 'unihack-22a02',
    authDomain: 'unihack-22a02.firebaseapp.com',
    storageBucket: 'unihack-22a02.appspot.com',
    measurementId: 'G-LYTGHMPT1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG-YCoHP4drwAXHtlC9UiGyngtrQbDG1g',
    appId: '1:148842405278:android:0033952150f8737c5aca8f',
    messagingSenderId: '148842405278',
    projectId: 'unihack-22a02',
    storageBucket: 'unihack-22a02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSSHUibm1pltzaZx1PNQFm70t_GvKnHNg',
    appId: '1:148842405278:ios:4616f6926410bef45aca8f',
    messagingSenderId: '148842405278',
    projectId: 'unihack-22a02',
    storageBucket: 'unihack-22a02.appspot.com',
    iosClientId: '148842405278-2dhlfj0et2bps1h86pb8c6bs1f2vmqmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.unihack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSSHUibm1pltzaZx1PNQFm70t_GvKnHNg',
    appId: '1:148842405278:ios:4616f6926410bef45aca8f',
    messagingSenderId: '148842405278',
    projectId: 'unihack-22a02',
    storageBucket: 'unihack-22a02.appspot.com',
    iosClientId: '148842405278-2dhlfj0et2bps1h86pb8c6bs1f2vmqmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.unihack',
  );
}
